// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';


function fill(a, b, c, d, e, f) {
  return /* tuple */[
          /* [] */0,
          /* [] */0
        ];
}

exports.fill = fill;
/* No side effect */
