// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Tools$MyNewProject = require("./Tools.bs.js");
var Filler$MyNewProject = require("./Filler.bs.js");

function solve(hContext, k) {
  var f = k[1];
  var u = k[0];
  if (!u) {
    return /* tuple */[
            f,
            hContext
          ];
  }
  var match = u[0];
  var h = match[0];
  var match$1 = Tools$MyNewProject.lookup(h, hContext);
  Filler$MyNewProject.fill(hContext, f, match$1[0], h, match$1[1], match[1]);
  return /* tuple */[
          /* [] */0,
          /* [] */0
        ];
}

exports.solve = solve;
/* No side effect */
