// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Pervasives = require("bs-platform/lib/js/pervasives.js");

function add(x, y) {
  return x + y | 0;
}

Pervasives.print_int(10);

Pervasives.print_string("\n");

exports.add = add;
/*  Not a pure module */
